insert into stock (quantity, location_in_store, store_name, apparel_id) values (140, 'JI28', 'isetan', 22);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (129, 'CW93', 'takashimaya', 11);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (249, 'ST00', 'topshop', 2);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (133, 'NK18', 'cotton on', 17);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (208, 'TN19', 'isetan', 10);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (334, 'KT01', 'zara', 11);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (152, 'XK23', 'forever 21', 29);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (257, 'KA85', 'zara', 2);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (375, 'NF66', 'uniqlo', 9);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (128, 'NZ22', 'h&m', 18);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (126, 'ZA76', 'uniqlo', 17);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (248, 'MF64', 'topshop', 13);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (142, 'DQ42', 'uniqlo', 14);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (198, 'CQ79', 'forever 21', 33);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (398, 'AE51', 'takashimaya', 10);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (338, 'WO40', 'uniqlo', 12);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (394, 'SJ28', 'takashimaya', 29);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (379, 'VM49', 'forever 21', 45);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (361, 'ER61', 'topshop', 5);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (121, 'NP77', 'uniqlo', 15);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (103, 'LC10', 'forever 21', 11);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (146, 'YW55', 'h&m', 4);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (206, 'EX26', 'topshop', 7);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (289, 'RU48', 'forever 21', 42);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (257, 'QW81', 'zara', 34);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (116, 'KO23', 'h&m', 35);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (369, 'BC63', 'takashimaya', 12);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (213, 'LX48', 'forever 21', 50);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (200, 'GO98', 'forever 21', 43);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (172, 'GH27', 'zara', 21);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (361, 'UT41', 'isetan', 32);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (385, 'HC86', 'uniqlo', 16);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (395, 'NK06', 'forever 21', 26);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (118, 'DH73', 'forever 21', 1);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (170, 'IN58', 'forever 21', 7);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (162, 'VR72', 'zara', 12);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (373, 'SR31', 'cotton on', 1);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (383, 'CU79', 'takashimaya', 18);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (129, 'QD66', 'uniqlo', 36);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (391, 'OS10', 'forever 21', 32);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (122, 'QO06', 'zara', 6);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (203, 'GU87', 'cotton on', 33);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (357, 'ON93', 'forever 21', 40);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (289, 'JU77', 'zara', 23);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (347, 'WO80', 'topshop', 16);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (275, 'OQ87', 'forever 21', 38);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (163, 'QG30', 'uniqlo', 35);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (245, 'SP49', 'h&m', 42);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (134, 'BW30', 'isetan', 19);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (192, 'VU69', 'zara', 3);

