
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (1, 'blouse', 'h&m', 'Daniel-Walker', 'casual', 'Black', '3XL', '$14.25', 'image1');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (2, 'blouse', 'h&m', 'Thompson LLC', 'casual', 'Grey', 'XL', '$56.25', 'image2');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (3, 'blouse', 'h&m', 'Wisoky-Upton', 'casual', 'Pink', '2XL', '$85.33', 'image3');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (4, 'blouse', 'h&m', 'Ratke, Brekke and Quitzon', 'casual', 'Blue', 'S', '$23.60', 'image4');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (5, 'jacket', 'forever 21', 'Smith, Volkman and Collier', 'formal', 'Black', 'L', '$64.13', 'image5');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (6, 'hoodie', 'topshop', 'Weissnat, Frami and Block', 'winter', 'White', 'L', '$86.72', 'image6');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (7, 'shorts', 'topmen', 'Johns-Oberbrunner', 'casual', 'Floral', '3XL', '$85.22', 'image7');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (8, 'shirt', 'topmen', 'Frami Inc', 'spring', 'Maroon', 'M', '$18.05', 'image8');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (9, 'jeans', 'h&m', 'Vandervort-Reynolds', 'fall', 'Blue', 'XS', '$67.62', 'image9');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (10, 'dress', 'topshop', 'Jerde, Kris and Kuvalis', 'casual', 'Red', 'S', '$77.22', 'image10');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (11, 'jacket', 'topmen', 'Kuphal, Wunsch and Kautzer', 'spring', 'Black', 'M', '$17.71', 'image11');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (12, 'shorts', 'cotton on', 'Osinski-Von', 'spring', 'Green', 'L', '$72.78', 'image12');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (13, 'croptop', 'temt', 'Dickens Group', 'casual', 'Black', '3XL', '$12.50', 'image13');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (14, 'round neck t-shirt', 'topmen', 'Connell, Harber and Thiel', 'casual', 'Grey', 'L', '$49.50', 'image14');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (15, 'shorts', 'forever 21', 'McCullough LLC', 'casual', 'Fuscia', 'M', '$90.05', 'image15');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (16, 'dress', 'topshop', 'DuBuque-Lowe', 'casual', 'Multi', 'S', '$55.25', 'image16');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (17, 'dress', 'temt', 'Mraz Inc', 'summer', 'Floral', '3XL', '$15.21', 'image17');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (18, 'hoodie', 'h&m', 'Schuster-Kohler', 'fall', 'Grey', 'XL', '$62.09', 'image18');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (19, 'dress', 'forever 21', 'Lueilwitz and Sons', 'winter', 'Navy', 'XL', '$55.09', 'image19');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (20, 'round neck t-shirt', 'topmen', 'Walker-McKenzie', 'summer', 'Puce', 'XS', '$71.92', 'image20');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (21, 'jacket', 'temt', 'Kertzmann-Bosco', 'formal', 'Indigo', '2XL', '$31.63', 'image21');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (22, 'jeans', 'temt', 'Haley-Lueilwitz', 'summer', 'Orange', '2XL', '$96.72', 'image22');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (23, 'round neck t-shirt', 'temt', 'Block-Mayer', 'summer', 'Navy', '3XL', '$63.84', 'image23');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (24, 'jacket', 'temt', 'Trantow Inc', 'spring', 'Black', '3XL', '$56.07', 'image24');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (25, 'jeans', 'h&m', 'Schulist Inc', 'winter', 'Blue', 'XL', '$63.55', 'image25');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (26, 'shorts', 'topshop', 'Reynolds, Oberbrunner and Towne', 'casual', 'Mauv', '3XL', '$41.28', 'image26');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (27, 'jacket', 'forever 21', 'Turcotte Inc', 'spring', 'Khaki', 'S', '$16.82', 'image27');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (28, 'hoodie', 'forever 21', 'Schaden LLC', 'fall', 'Yellow', '2XL', '$60.45', 'image28');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (29, 'jacket', 'cotton on', 'Goyette LLC', 'spring', 'Navy', 'XL', '$37.06', 'image29');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (30, 'jeans', 'topmen', 'Steuber-Funk', 'spring', 'Denim', 'XS', '$23.03', 'image30');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (31, 'skirt', 'topshop', 'Shields-Feeney', 'fall', 'White', 'S', '$61.76', 'image31');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (32, 'shirt', 'topmen', 'Schaefer-Feil', 'formal', 'Maroon', '3XL', '$20.94', 'image32');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (33, 'dress', 'temt', 'Weissnat LLC', 'winter', 'Floral', '3XL', '$84.32', 'image33');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (34, 'jeans', 'forever 21', 'Kozey-Halvorson', 'summer', 'Denim', '3XL', '$91.92', 'image34');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (35, 'round neck t-shirt', 'topshop', 'Tillman and Sons', 'casual', 'Black', '3XL', '$34.16', 'image35');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (36, 'hoodie', 'h&m', 'Schultz LLC', 'fall', 'Yellow', 'L', '$85.34', 'image36');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (37, 'hoodie', 'cotton on', 'Torphy Group', 'casual', 'Grey', 'XL', '$17.76', 'image37');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (38, 'jacket', 'h&m', 'Mayert LLC', 'spring', 'Brown', 'XL', '$25.19', 'image38');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (39, 'dress', 'forever 21', 'Gottlieb Inc', 'fall', 'Teal', 'L', '$52.56', 'image39');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (40, 'jeans', 'topmen', 'Kling Group', 'spring', 'Grey', '2XL', '$97.32', 'image40');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (41, 'blouse', 'cotton on', 'Tromp-Luettgen', 'fall', 'Pink', 'XS', '$87.71', 'image41');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (42, 'jeans', 'temt', 'Moen, Ruecker and Reynolds', 'summer', 'Denim', 'S', '$86.65', 'image42');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (43, 'hoodie', 'topshop', 'Kuphal-Greenfelder', 'winter', 'Grey', 'S', '$46.82', 'image43');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (44, 'jacket', 'topshop', 'Schumm Inc', 'spring', 'Brown', 'XL', '$42.57', 'image44');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (45, 'shorts', 'h&m', 'Schoen Inc', 'casual', 'Denim', '3XL', '$53.17', 'image45');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (46, 'dress', 'h&m', 'Buckridge-Wintheiser', 'spring', 'Green', '2XL', '$59.89', 'image46');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (47, 'blouse', 'topshop', 'Ferry, Gleason and Hara', 'casual', 'Pink', 'XL', '$83.03', 'image47');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (48, 'jacket', 'cotton on', 'Jast-Raynor', 'casual', 'Blue', '3XL', '$78.19', 'image48');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (49, 'shorts', 'topmen', 'Kirlin-Kassulke', 'winter', 'Green', 'XS', '$70.82', 'image49');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (50, 'round neck t-shirt', 'forever 21', 'Wilkinson LLC', 'casual', 'Khaki', 'S', '$53.15', 'image50');

