
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (1, 'blouse', 'h&m', 'Daniel-Walker', 'casual', 'Black', '3XL', '14.25', 'image1');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (2, 'blouse', 'h&m', 'Thompson LLC', 'casual', 'Grey', 'XL', '56.25', 'image2');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (3, 'blouse', 'h&m', 'Wisoky-Upton', 'casual', 'Pink', '2XL', '85.33', 'image3');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (4, 'blouse', 'h&m', 'Ratke, Brekke and Quitzon', 'casual', 'Blue', 'S', '23.60', 'image4');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (5, 'jacket', 'forever 21', 'Smith, Volkman and Collier', 'formal', 'Black', 'L', '64.13', 'image5');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (6, 'hoodie', 'topshop', 'Weissnat, Frami and Block', 'winter', 'White', 'L', '86.72', 'image6');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (7, 'shorts', 'topmen', 'Johns-Oberbrunner', 'casual', 'Floral', '3XL', '85.22', 'image7');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (8, 'shirt', 'topmen', 'Frami Inc', 'spring', 'Maroon', 'M', '18.05', 'image8');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (9, 'jeans', 'h&m', 'Vandervort-Reynolds', 'fall', 'Blue', 'XS', '67.62', 'image9');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (10, 'dress', 'topshop', 'Jerde, Kris and Kuvalis', 'casual', 'Red', 'S', '77.22', 'image10');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (11, 'jacket', 'topmen', 'Kuphal, Wunsch and Kautzer', 'spring', 'Black', 'M', '17.71', 'image11');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (12, 'shorts', 'cotton on', 'Osinski-Von', 'spring', 'Green', 'L', '72.78', 'image12');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (13, 'croptop', 'temt', 'Dickens Group', 'casual', 'Black', '3XL', '12.50', 'image13');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (14, 'round neck t-shirt', 'topmen', 'Connell, Harber and Thiel', 'casual', 'Grey', 'L', '49.50', 'image14');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (15, 'shorts', 'forever 21', 'McCullough LLC', 'casual', 'Fuscia', 'M', '90.05', 'image15');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (16, 'dress', 'topshop', 'DuBuque-Lowe', 'casual', 'Multi', 'S', '55.25', 'image16');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (17, 'dress', 'temt', 'Mraz Inc', 'summer', 'Floral', '3XL', '15.21', 'image17');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (18, 'hoodie', 'h&m', 'Schuster-Kohler', 'fall', 'Grey', 'XL', '62.09', 'image18');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (19, 'dress', 'forever 21', 'Lueilwitz and Sons', 'winter', 'Navy', 'XL', '55.09', 'image19');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (20, 'round neck t-shirt', 'topmen', 'Walker-McKenzie', 'summer', 'Puce', 'XS', '71.92', 'image20');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (21, 'jacket', 'temt', 'Kertzmann-Bosco', 'formal', 'Indigo', '2XL', '31.63', 'image21');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (22, 'jeans', 'temt', 'Haley-Lueilwitz', 'summer', 'Orange', '2XL', '96.72', 'image22');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (23, 'round neck t-shirt', 'temt', 'Block-Mayer', 'summer', 'Navy', '3XL', '63.84', 'image23');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (24, 'jacket', 'temt', 'Trantow Inc', 'spring', 'Black', '3XL', '56.07', 'image24');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (25, 'jeans', 'h&m', 'Schulist Inc', 'winter', 'Blue', 'XL', '63.55', 'image25');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (26, 'shorts', 'topshop', 'Reynolds, Oberbrunner and Towne', 'casual', 'Mauv', '3XL', '41.28', 'image26');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (27, 'jacket', 'forever 21', 'Turcotte Inc', 'spring', 'Khaki', 'S', '16.82', 'image27');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (28, 'hoodie', 'forever 21', 'Schaden LLC', 'fall', 'Yellow', '2XL', '60.45', 'image28');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (29, 'jacket', 'cotton on', 'Goyette LLC', 'spring', 'Navy', 'XL', '37.06', 'image29');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (30, 'jeans', 'topmen', 'Steuber-Funk', 'spring', 'Denim', 'XS', '23.03', 'image30');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (31, 'skirt', 'topshop', 'Shields-Feeney', 'fall', 'White', 'S', '61.76', 'image31');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (32, 'shirt', 'topmen', 'Schaefer-Feil', 'formal', 'Maroon', '3XL', '20.94', 'image32');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (33, 'dress', 'temt', 'Weissnat LLC', 'winter', 'Floral', '3XL', '84.32', 'image33');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (34, 'jeans', 'forever 21', 'Kozey-Halvorson', 'summer', 'Denim', '3XL', '91.92', 'image34');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (35, 'round neck t-shirt', 'topshop', 'Tillman and Sons', 'casual', 'Black', '3XL', '34.16', 'image35');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (36, 'hoodie', 'h&m', 'Schultz LLC', 'fall', 'Yellow', 'L', '85.34', 'image36');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (37, 'hoodie', 'cotton on', 'Torphy Group', 'casual', 'Grey', 'XL', '17.76', 'image37');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (38, 'jacket', 'h&m', 'Mayert LLC', 'spring', 'Brown', 'XL', '25.19', 'image38');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (39, 'dress', 'forever 21', 'Gottlieb Inc', 'fall', 'Teal', 'L', '52.56', 'image39');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (40, 'jeans', 'topmen', 'Kling Group', 'spring', 'Grey', '2XL', '97.32', 'image40');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (41, 'blouse', 'cotton on', 'Tromp-Luettgen', 'fall', 'Pink', 'XS', '87.71', 'image41');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (42, 'jeans', 'temt', 'Moen, Ruecker and Reynolds', 'summer', 'Denim', 'S', '86.65', 'image42');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (43, 'hoodie', 'topshop', 'Kuphal-Greenfelder', 'winter', 'Grey', 'S', '46.82', 'image43');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (44, 'jacket', 'topshop', 'Schumm Inc', 'spring', 'Brown', 'XL', '42.57', 'image44');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (45, 'shorts', 'h&m', 'Schoen Inc', 'casual', 'Denim', '3XL', '53.17', 'image45');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (46, 'dress', 'h&m', 'Buckridge-Wintheiser', 'spring', 'Green', '2XL', '59.89', 'image46');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (47, 'blouse', 'topshop', 'Ferry, Gleason and Hara', 'casual', 'Pink', 'XL', '83.03', 'image47');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (48, 'jacket', 'cotton on', 'Jast-Raynor', 'casual', 'Blue', '3XL', '78.19', 'image48');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (49, 'shorts', 'topmen', 'Kirlin-Kassulke', 'winter', 'Green', 'XS', '70.82', 'image49');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (50, 'round neck t-shirt', 'forever 21', 'Wilkinson LLC', 'casual', 'Khaki', 'S', '53.15', 'image50');

insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (51, 'blouse', 'h&m', 'Daniel-Walker', 'casual', 'Black', 'L', '14.25', 'image1');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (52, 'blouse', 'h&m', 'Thompson LLC', 'casual', 'Grey', 'L', '56.25', 'image2');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (53, 'blouse', 'h&m', 'Wisoky-Upton', 'casual', 'Pink', 'XL', '85.33', 'image3');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (54, 'blouse', 'h&m', 'Ratke, Brekke and Quitzon', 'casual', 'Blue', 'M', '23.60', 'image4');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (55, 'jacket', 'forever 21', 'Smith, Volkman and Collier', 'formal', 'Black', 'M', '64.13', 'image5');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (56, 'hoodie', 'topshop', 'Weissnat, Frami and Block', 'winter', 'White', 'M', '86.72', 'image6');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (57, 'shorts', 'topmen', 'Johns-Oberbrunner', 'casual', 'Floral', '2XL', '85.22', 'image7');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (58, 'shirt', 'topmen', 'Frami Inc', 'spring', 'Maroon', 'M', '18.05', 'image8');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (59, 'jeans', 'h&m', 'Vandervort-Reynolds', 'fall', 'Blue', 'S', '67.62', 'image9');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (60, 'dress', 'topshop', 'Jerde, Kris and Kuvalis', 'casual', 'Red', 'M', '77.22', 'image10');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (61, 'jacket', 'topmen', 'Kuphal, Wunsch and Kautzer', 'spring', 'Black', 'M', '17.71', 'image11');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (62, 'shorts', 'cotton on', 'Osinski-Von', 'spring', 'Green', 'M', '72.78', 'image12');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (63, 'croptop', 'temt', 'Dickens Group', 'casual', 'Black', '2XL', '12.50', 'image13');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (64, 'round neck t-shirt', 'topmen', 'Connell, Harber and Thiel', 'casual', 'Grey', 'M', '49.50', 'image14');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (65, 'shorts', 'forever 21', 'McCullough LLC', 'casual', 'Fuscia', 'M', '90.05', 'image15');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (66, 'dress', 'topshop', 'DuBuque-Lowe', 'casual', 'Multi', 'M', '55.25', 'image16');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (67, 'dress', 'temt', 'Mraz Inc', 'summer', 'Floral', '2XL', '15.21', 'image17');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (68, 'hoodie', 'h&m', 'Schuster-Kohler', 'fall', 'Grey', 'L', '62.09', 'image18');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (69, 'dress', 'forever 21', 'Lueilwitz and Sons', 'winter', 'Navy', 'L', '55.09', 'image19');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (70, 'round neck t-shirt', 'topmen', 'Walker-McKenzie', 'summer', 'Puce', 'S', '71.92', 'image20');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (71, 'jacket', 'temt', 'Kertzmann-Bosco', 'formal', 'Indigo', 'XL', '31.63', 'image21');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (72, 'jeans', 'temt', 'Haley-Lueilwitz', 'summer', 'Orange', 'XL', '96.72', 'image22');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (73, 'round neck t-shirt', 'temt', 'Block-Mayer', 'summer', 'Navy', '2XL', '63.84', 'image23');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (74, 'jacket', 'temt', 'Trantow Inc', 'spring', 'Black', '2XL', '56.07', 'image24');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (75, 'jeans', 'h&m', 'Schulist Inc', 'winter', 'Blue', 'L', '63.55', 'image25');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (76, 'shorts', 'topshop', 'Reynolds, Oberbrunner and Towne', 'casual', 'Mauv', '2XL', '41.28', 'image26');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (77, 'jacket', 'forever 21', 'Turcotte Inc', 'spring', 'Khaki', 'M', '16.82', 'image27');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (78, 'hoodie', 'forever 21', 'Schaden LLC', 'fall', 'Yellow', 'XL', '60.45', 'image28');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (79, 'jacket', 'cotton on', 'Goyette LLC', 'spring', 'Navy', 'L', '37.06', 'image29');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (80, 'jeans', 'topmen', 'Steuber-Funk', 'spring', 'Denim', 'S', '23.03', 'image30');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (81, 'skirt', 'topshop', 'Shields-Feeney', 'fall', 'White', 'M', '61.76', 'image31');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (82, 'shirt', 'topmen', 'Schaefer-Feil', 'formal', 'Maroon', 'XL', '20.94', 'image32');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (83, 'dress', 'temt', 'Weissnat LLC', 'winter', 'Floral', 'XL', '84.32', 'image33');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (84, 'jeans', 'forever 21', 'Kozey-Halvorson', 'summer', 'Denim', 'XL', '91.92', 'image34');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (85, 'round neck t-shirt', 'topshop', 'Tillman and Sons', 'casual', 'Black', 'XL', '34.16', 'image35');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (86, 'hoodie', 'h&m', 'Schultz LLC', 'fall', 'Yellow', 'M', '85.34', 'image36');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (87, 'hoodie', 'cotton on', 'Torphy Group', 'casual', 'Grey', 'M', '17.76', 'image37');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (88, 'jacket', 'h&m', 'Mayert LLC', 'spring', 'Brown', 'L', '25.19', 'image38');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (89, 'dress', 'forever 21', 'Gottlieb Inc', 'fall', 'Teal', 'M', '52.56', 'image39');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (90, 'jeans', 'topmen', 'Kling Group', 'spring', 'Grey', 'XL', '97.32', 'image40');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (91, 'blouse', 'cotton on', 'Tromp-Luettgen', 'fall', 'Pink', 'S', '87.71', 'image41');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (92, 'jeans', 'temt', 'Moen, Ruecker and Reynolds', 'summer', 'Denim', 'M', '86.65', 'image42');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (93, 'hoodie', 'topshop', 'Kuphal-Greenfelder', 'winter', 'Grey', 'M', '46.82', 'image43');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (94, 'jacket', 'topshop', 'Schumm Inc', 'spring', 'Brown', 'L', '42.57', 'image44');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (95, 'shorts', 'h&m', 'Schoen Inc', 'casual', 'Denim', '2XL', '53.17', 'image45');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (96, 'dress', 'h&m', 'Buckridge-Wintheiser', 'spring', 'Green', 'XL', '59.89', 'image46');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (97, 'blouse', 'topshop', 'Ferry, Gleason and Hara', 'casual', 'Pink', 'L', '83.03', 'image47');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (98, 'jacket', 'cotton on', 'Jast-Raynor', 'casual', 'Blue', '2XL', '78.19', 'image48');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (99, 'shorts', 'topmen', 'Kirlin-Kassulke', 'winter', 'Green', 'S', '70.82', 'image49');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (100, 'round neck t-shirt', 'forever 21', 'Wilkinson LLC', 'casual', 'Khaki', 'M', '53.15', 'image50');

insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (101, 'blouse', 'h&m', 'Daniel-Walker', 'casual', 'Black', 'M', '14.25', 'image1');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (102, 'blouse', 'h&m', 'Thompson LLC', 'casual', 'Grey', 'M', '56.25', 'image2');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (103, 'blouse', 'h&m', 'Wisoky-Upton', 'casual', 'Pink', 'L', '85.33', 'image3');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (104, 'blouse', 'h&m', 'Ratke, Brekke and Quitzon', 'casual', 'Blue', 'S', '23.60', 'image4');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (105, 'jacket', 'forever 21', 'Smith, Volkman and Collier', 'formal', 'Black', 'S', '64.13', 'image5');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (106, 'hoodie', 'topshop', 'Weissnat, Frami and Block', 'winter', 'White', 'S', '86.72', 'image6');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (107, 'shorts', 'topmen', 'Johns-Oberbrunner', 'casual', 'Floral', 'XL', '85.22', 'image7');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (108, 'shirt', 'topmen', 'Frami Inc', 'spring', 'Maroon', 'S', '18.05', 'image8');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (109, 'jeans', 'h&m', 'Vandervort-Reynolds', 'fall', 'Blue', 'XS', '67.62', 'image9');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (110, 'dress', 'topshop', 'Jerde, Kris and Kuvalis', 'casual', 'Red', 'S', '77.22', 'image10');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (111, 'jacket', 'topmen', 'Kuphal, Wunsch and Kautzer', 'spring', 'Black', 'S', '17.71', 'image11');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (112, 'shorts', 'cotton on', 'Osinski-Von', 'spring', 'Green', 'S', '72.78', 'image12');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (113, 'croptop', 'temt', 'Dickens Group', 'casual', 'Black', 'XL', '12.50', 'image13');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (114, 'round neck t-shirt', 'topmen', 'Connell, Harber and Thiel', 'casual', 'Grey', 'S', '49.50', 'image14');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (115, 'shorts', 'forever 21', 'McCullough LLC', 'casual', 'Fuscia', 'S', '90.05', 'image15');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (116, 'dress', 'topshop', 'DuBuque-Lowe', 'casual', 'Multi', 'S', '55.25', 'image16');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (117, 'dress', 'temt', 'Mraz Inc', 'summer', 'Floral', 'XL', '15.21', 'image17');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (118, 'hoodie', 'h&m', 'Schuster-Kohler', 'fall', 'Grey', 'M', '62.09', 'image18');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (119, 'dress', 'forever 21', 'Lueilwitz and Sons', 'winter', 'Navy', 'M', '55.09', 'image19');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (120, 'round neck t-shirt', 'topmen', 'Walker-McKenzie', 'summer', 'Puce', 'XS', '71.92', 'image20');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (121, 'jacket', 'temt', 'Kertzmann-Bosco', 'formal', 'Indigo', 'L', '31.63', 'image21');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (122, 'jeans', 'temt', 'Haley-Lueilwitz', 'summer', 'Orange', 'L', '96.72', 'image22');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (123, 'round neck t-shirt', 'temt', 'Block-Mayer', 'summer', 'Navy', 'XL', '63.84', 'image23');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (124, 'jacket', 'temt', 'Trantow Inc', 'spring', 'Black', 'XL', '56.07', 'image24');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (125, 'jeans', 'h&m', 'Schulist Inc', 'winter', 'Blue', 'M', '63.55', 'image25');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (126, 'shorts', 'topshop', 'Reynolds, Oberbrunner and Towne', 'casual', 'Mauv', 'XL', '41.28', 'image26');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (127, 'jacket', 'forever 21', 'Turcotte Inc', 'spring', 'Khaki', 'S', '16.82', 'image27');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (128, 'hoodie', 'forever 21', 'Schaden LLC', 'fall', 'Yellow', 'L', '60.45', 'image28');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (129, 'jacket', 'cotton on', 'Goyette LLC', 'spring', 'Navy', 'M', '37.06', 'image29');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (130, 'jeans', 'topmen', 'Steuber-Funk', 'spring', 'Denim', 'XS', '23.03', 'image30');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (131, 'skirt', 'topshop', 'Shields-Feeney', 'fall', 'White', 'S', '61.76', 'image31');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (132, 'shirt', 'topmen', 'Schaefer-Feil', 'formal', 'Maroon', 'L', '20.94', 'image32');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (133, 'dress', 'temt', 'Weissnat LLC', 'winter', 'Floral', 'L', '84.32', 'image33');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (134, 'jeans', 'forever 21', 'Kozey-Halvorson', 'summer', 'Denim', 'L', '91.92', 'image34');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (135, 'round neck t-shirt', 'topshop', 'Tillman and Sons', 'casual', 'Black', 'L', '34.16', 'image35');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (136, 'hoodie', 'h&m', 'Schultz LLC', 'fall', 'Yellow', 'S', '85.34', 'image36');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (137, 'hoodie', 'cotton on', 'Torphy Group', 'casual', 'Grey', 'S', '17.76', 'image37');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (138, 'jacket', 'h&m', 'Mayert LLC', 'spring', 'Brown', 'M', '25.19', 'image38');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (139, 'dress', 'forever 21', 'Gottlieb Inc', 'fall', 'Teal', 'S', '52.56', 'image39');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (140, 'jeans', 'topmen', 'Kling Group', 'spring', 'Grey', 'L', '97.32', 'image40');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (141, 'blouse', 'cotton on', 'Tromp-Luettgen', 'fall', 'Pink', 'M', '87.71', 'image41');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (142, 'jeans', 'temt', 'Moen, Ruecker and Reynolds', 'summer', 'Denim', 'S', '86.65', 'image42');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (143, 'hoodie', 'topshop', 'Kuphal-Greenfelder', 'winter', 'Grey', 'S', '46.82', 'image43');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (144, 'jacket', 'topshop', 'Schumm Inc', 'spring', 'Brown', 'M', '42.57', 'image44');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (145, 'shorts', 'h&m', 'Schoen Inc', 'casual', 'Denim', 'XL', '53.17', 'image45');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (146, 'dress', 'h&m', 'Buckridge-Wintheiser', 'spring', 'Green', 'L', '59.89', 'image46');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (147, 'blouse', 'topshop', 'Ferry, Gleason and Hara', 'casual', 'Pink', 'M', '83.03', 'image47');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (148, 'jacket', 'cotton on', 'Jast-Raynor', 'casual', 'Blue', 'XL', '78.19', 'image48');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (149, 'shorts', 'topmen', 'Kirlin-Kassulke', 'winter', 'Green', 'XS', '70.82', 'image49');
insert into apparel (id, name, brand, manufacturer, style, color, size, price, image) values (150, 'round neck t-shirt', 'forever 21', 'Wilkinson LLC', 'casual', 'Khaki', 'S', '53.15', 'image50');