insert into stock (quantity, location_in_store, store_name, apparel_id) values (177, 'EX73', 'trump tower', 6);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (70, 'ZY07', 'uniqlo', 7);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (89, 'LA17', 'the moon', 5);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (70, 'JG76', 'the moon', 2);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (160, 'NF44', 'topman', 10);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (2, 'SR72', 'topman', 8);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (122, 'DP75', 'uniqlo', 2);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (115, 'NX97', 'takashimaya', 7);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (72, 'SL45', 'starbucks', 10);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (34, 'RR61', 'zara', 6);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (40, 'GK30', 'topshop', 7);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (89, 'KP97', 'trump tower', 10);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (49, 'VG12', 'isetan', 10);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (65, 'YH57', 'uniqlo', 9);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (31, 'CV12', 'isetan', 2);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (126, 'XB87', 'forever 21', 9);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (51, 'IA93', 'cotton on', 4);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (62, 'ND43', 'topman', 5);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (174, 'FR62', 'topshop', 6);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (110, 'HN83', 'topman', 10);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (152, 'TE81', 'h&m', 4);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (119, 'LK76', 'the moon', 7);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (109, 'JF94', 'the moon', 9);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (94, 'VP84', 'cotton on', 10);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (37, 'HQ51', 'isetan', 10);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (168, 'MO69', 'trump tower', 5);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (9, 'XH87', 'trump tower', 5);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (161, 'SI30', 'h&m', 7);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (152, 'KY68', 'forever 21', 7);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (16, 'KK10', 'topman', 6);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (154, 'II35', 'trump tower', 5);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (104, 'MG71', 'topman', 7);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (185, 'UO65', 'topshop', 7);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (7, 'TY43', 'starbucks', 6);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (106, 'DK85', 'h&m', 3);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (168, 'MW42', 'trump tower', 10);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (29, 'LG98', 'cotton on', 10);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (76, 'DN01', 'starbucks', 6);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (133, 'SB36', 'starbucks', 9);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (161, 'MX61', 'isetan', 1);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (98, 'SS19', 'topshop', 7);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (155, 'MY23', 'trump tower', 10);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (141, 'FH52', 'starbucks', 10);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (92, 'ZC20', 'the moon', 3);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (154, 'SU64', 'forever 21', 4);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (85, 'DR65', 'uniqlo', 2);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (165, 'UE49', 'topshop', 4);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (103, 'LQ76', 'uniqlo', 6);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (194, 'BA50', 'forever 21', 4);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (131, 'TM78', 'com1 basement', 6);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (123, 'CI85', 'takashimaya', 5);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (43, 'UM66', 'zara', 7);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (87, 'UM33', 'com1 basement', 10);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (170, 'RZ15', 'h&m', 5);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (103, 'HB55', 'takashimaya', 3);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (83, 'YJ70', 'uniqlo', 5);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (118, 'KG70', 'trump tower', 10);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (33, 'SL85', 'the moon', 3);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (171, 'WJ30', 'the moon', 8);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (34, 'SB70', 'starbucks', 4);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (118, 'QN11', 'trump tower', 9);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (95, 'ZO96', 'cotton on', 10);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (51, 'SP54', 'starbucks', 4);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (125, 'XJ01', 'uniqlo', 5);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (148, 'QJ17', 'forever 21', 7);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (187, 'DE54', 'the moon', 8);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (98, 'HP23', 'zara', 9);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (100, 'ET25', 'trump tower', 6);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (103, 'VU20', 'takashimaya', 9);
insert into stock (quantity, location_in_store, store_name, apparel_id) values (156, 'WQ87', 'topshop', 8);